# Formerly known as pepecoin (PEPE), we primarily accept memetic (MEME) for donations. 
# Your donations will go towards hosting the training models and LLMs that our API will eventually connect to
# Other coins will be considered upon request, however we will never deal in FIAT currencies at the request of the OS itself.

memetic: smYk4AvFhgrYerpR3VM4F8UgUqoqjNc4y7TQLjWf1hxAi7zFzDW1ntFYCiYjnZbi9cieL3QwoxQhbTZWiS8tTkh9GUSL2PXKAMejkv
